//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalettePicker.Resources.SaveClassResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SaveClass {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SaveClass() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PalettePicker.Resources.SaveClassResources.SaveClass", typeof(SaveClass).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is empty..
        /// </summary>
        internal static string FileEmptyErr {
            get {
                return ResourceManager.GetString("FileEmptyErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file is not a valid palette JSON file..
        /// </summary>
        internal static string FileErrMsg {
            get {
                return ResourceManager.GetString("FileErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Error.
        /// </summary>
        internal static string FileErrTitle {
            get {
                return ResourceManager.GetString("FileErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist..
        /// </summary>
        internal static string FileNotExistErr {
            get {
                return ResourceManager.GetString("FileNotExistErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not a JSON file..
        /// </summary>
        internal static string FileNotJSONErr {
            get {
                return ResourceManager.GetString("FileNotJSONErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while extracting JSON save file with following error message: .
        /// </summary>
        internal static string FileReadErrMsg {
            get {
                return ResourceManager.GetString("FileReadErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Read Error.
        /// </summary>
        internal static string FileReadErrTitle {
            get {
                return ResourceManager.GetString("FileReadErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folder selected.
        /// </summary>
        internal static string FolderSelectErrMsg {
            get {
                return ResourceManager.GetString("FolderSelectErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Error.
        /// </summary>
        internal static string FolderSelectErrTitle {
            get {
                return ResourceManager.GetString("FolderSelectErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON data was null..
        /// </summary>
        internal static string JSONNullErr {
            get {
                return ResourceManager.GetString("JSONNullErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing key required: .
        /// </summary>
        internal static string MissingKeyErr {
            get {
                return ResourceManager.GetString("MissingKeyErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file: .
        /// </summary>
        internal static string ReadingErr {
            get {
                return ResourceManager.GetString("ReadingErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where to save the palette.
        /// </summary>
        internal static string SaveDialog {
            get {
                return ResourceManager.GetString("SaveDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while trying to save file. Path is either empty or does not exist..
        /// </summary>
        internal static string SaveErrMsg {
            get {
                return ResourceManager.GetString("SaveErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Error.
        /// </summary>
        internal static string SaveErrTitle {
            get {
                return ResourceManager.GetString("SaveErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the color palette.
        /// </summary>
        internal static string SelectDialog {
            get {
                return ResourceManager.GetString("SelectDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected.
        /// </summary>
        internal static string SelectErrMsg {
            get {
                return ResourceManager.GetString("SelectErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Error.
        /// </summary>
        internal static string SelectErrTitle {
            get {
                return ResourceManager.GetString("SelectErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not contain the correct number of value pairs..
        /// </summary>
        internal static string WrongPairCountErr {
            get {
                return ResourceManager.GetString("WrongPairCountErr", resourceCulture);
            }
        }
    }
}
