//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalettePicker.Resources.ColorPickerWindowResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ColorPickerWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColorPickerWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PalettePicker.Resources.ColorPickerWindowResources.ColorPickerWindow", typeof(ColorPickerWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to quit without saving progress?.
        /// </summary>
        internal static string ExitConfirmationText {
            get {
                return ResourceManager.GetString("ExitConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Confirmation.
        /// </summary>
        internal static string ExitConfirmationTitle {
            get {
                return ResourceManager.GetString("ExitConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Hue:.
        /// </summary>
        internal static string HueText {
            get {
                return ResourceManager.GetString("HueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inputed hex was not in the right format. Reverting to the original color..
        /// </summary>
        internal static string InputWarningText {
            get {
                return ResourceManager.GetString("InputWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Warning.
        /// </summary>
        internal static string InputWarningTitle {
            get {
                return ResourceManager.GetString("InputWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Luminance:.
        /// </summary>
        internal static string LuminanceText {
            get {
                return ResourceManager.GetString("LuminanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary 1.
        /// </summary>
        internal static string Primary1Text {
            get {
                return ResourceManager.GetString("Primary1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary 2.
        /// </summary>
        internal static string Primary2Text {
            get {
                return ResourceManager.GetString("Primary2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Saturation:.
        /// </summary>
        internal static string SaturationText {
            get {
                return ResourceManager.GetString("SaturationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary 1.
        /// </summary>
        internal static string Secondary1Text {
            get {
                return ResourceManager.GetString("Secondary1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary 2.
        /// </summary>
        internal static string Secondary2Text {
            get {
                return ResourceManager.GetString("Secondary2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextText {
            get {
                return ResourceManager.GetString("TextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Picker.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
